apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - protocol: TCP
      name: myblog
      port: 3000
      targetPort: 3000
    - protocol: TCP
      name: api
      port: 4000
      targetPort: 4000
