global:
  scrape_interval: 15s # Définit à quelle fréquence Prometheus récupère les données

scrape_configs:
  - job_name: "kubernetes-pods"
    kubernetes_sd_configs:
      - role: pod

  - job_name: "kubernetes-nodes"
    kubernetes_sd_configs:
      - role: node
